apiVersion: batch/v1
kind: Job

metadata:
  name: completion-job
  namespace: cron

spec:
  completions: 3

  template:
    spec:
      restartPolicy: Never

      containers:
        - name: worker
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Processing one unit of work..."
              sleep 5
              echo "Work completed!"
