apiVersion: batch/v1
kind: Job

metadata:
  name: parallel-job
  namespace: cron

spec:
  completions: 6
  parallelism: 2

  template:
    spec:
      restartPolicy: Never

      containers:
        - name: worker
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Worker started: $(hostname)"
              sleep 10
              echo "Worker completed: $(hostname)"
